"""
Comprehensive IPC to BNS mapping data with landmark cases
This includes major sections and their transitions
"""

IPC_BNS_MAPPINGS = [
    {
        "ipc_section": "120A",
        "ipc_description": "Definition of criminal conspiracy",
        "ipc_text": "When two or more persons agree to do, or cause to be done, an illegal act, or an act which is not illegal by illegal means, such an agreement is designated a criminal conspiracy.",
        "bns_section": "61",
        "bns_description": "Criminal conspiracy",
        "bns_text": "When two or more persons agree to do, or cause to be done an illegal act, or an act which is not illegal by illegal means, such an agreement is designated a criminal conspiracy.",
        "has_changes": True,
        "change_type": "substantive",
        "change_summary": "Minor linguistic changes, core definition remains same",
        "category": "Criminal Conspiracy",
        "punishment": "Imprisonment up to 6 months or fine or both"
    },
    {
        "ipc_section": "120B",
        "ipc_description": "Punishment of criminal conspiracy",
        "ipc_text": "Whoever is a party to a criminal conspiracy to commit an offence punishable with death, imprisonment for life or rigorous imprisonment for a term of two years or upwards, shall be punished in the same manner as if he had abetted such offence.",
        "bns_section": "62",
        "bns_description": "Punishment of criminal conspiracy",
        "bns_text": "Whoever is a party to a criminal conspiracy to commit an offence punishable with death, imprisonment for life or rigorous imprisonment for a term of two years or upwards, shall be punished in the same manner as if he had abetted such offence.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No substantive changes",
        "category": "Criminal Conspiracy",
        "punishment": "Same as abetment of offence"
    },
    {
        "ipc_section": "121",
        "ipc_description": "Waging war against Government of India",
        "ipc_text": "Whoever wages war against the Government of India, or attempts to wage such war, or abets the waging of such war, shall be punished with death, or imprisonment for life and shall also be liable to fine.",
        "bns_section": "147",
        "bns_description": "Waging war against Government of India",
        "bns_text": "Whoever wages war against the Government of India, or attempts to wage such war, or abets the waging of such war, shall be punished with death, or imprisonment for life, and shall also be liable to fine.",
        "has_changes": False,
        "change_type": "linguistic",
        "change_summary": "Minor punctuation changes only",
        "category": "Offences Against the State",
        "punishment": "Death or life imprisonment and fine"
    },
    {
        "ipc_section": "124A",
        "ipc_description": "Sedition",
        "ipc_text": "Whoever, by words, either spoken or written, or by signs, or by visible representation, or otherwise, brings or attempts to bring into hatred or contempt, or excites or attempts to excite disaffection towards the Government established by law shall be punished with imprisonment for life, to which fine may be added, or with imprisonment which may extend to three years, to which fine may be added, or with fine.",
        "bns_section": "152",
        "bns_description": "Acts endangering sovereignty, unity and integrity of India",
        "bns_text": "Whoever, purposely or knowingly, by words, either spoken or written, or by signs, or by visible representation, or by electronic communication or by use of financial mean, or otherwise, excites or attempts to excite, secession or armed rebellion or subversive activities, or encourages feelings of separatist activities or endangers sovereignty or unity and integrity of India; shall be punished with imprisonment for life or with imprisonment which may extend to seven years and shall also be liable to fine.",
        "has_changes": True,
        "change_type": "substantive",
        "change_summary": "Significant changes: 'Sedition' replaced with acts endangering sovereignty. Requires 'purposely or knowingly'. Includes electronic communication. Higher punishment.",
        "category": "Offences Against the State",
        "punishment": "Life imprisonment or up to 7 years and fine"
    },
    {
        "ipc_section": "299",
        "ipc_description": "Culpable homicide",
        "ipc_text": "Whoever causes death by doing an act with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that he is likely by such act to cause death, commits the offence of culpable homicide.",
        "bns_section": "100",
        "bns_description": "Culpable homicide",
        "bns_text": "Whoever causes death by doing an act with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that he is likely by such act to cause death, commits the offence of culpable homicide.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes - definition remains identical",
        "category": "Offences Affecting Life",
        "punishment": "Varies based on circumstances"
    },
    {
        "ipc_section": "300",
        "ipc_description": "Murder",
        "ipc_text": "Except in the cases hereinafter excepted, culpable homicide is murder if the act by which the death is caused is done with the intention of causing death...",
        "bns_section": "101",
        "bns_description": "Murder",
        "bns_text": "Except in the cases hereinafter excepted, culpable homicide is murder if the act by which the death is caused is done with the intention of causing death, or with the intention of causing such bodily injury as the offender knows to be likely to cause the death of the person to whom the harm is caused...",
        "has_changes": False,
        "change_type": "linguistic",
        "change_summary": "Minor linguistic refinements, core definition unchanged",
        "category": "Offences Affecting Life",
        "punishment": "Death or life imprisonment and fine"
    },
    {
        "ipc_section": "302",
        "ipc_description": "Punishment for murder",
        "ipc_text": "Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.",
        "bns_section": "103",
        "bns_description": "Punishment for murder",
        "bns_text": "Whoever commits murder shall be punished with death or imprisonment for life, and shall also be liable to fine.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No substantive changes",
        "category": "Offences Affecting Life",
        "punishment": "Death or life imprisonment and fine"
    },
    {
        "ipc_section": "304",
        "ipc_description": "Punishment for culpable homicide not amounting to murder",
        "ipc_text": "Whoever commits culpable homicide not amounting to murder shall be punished with imprisonment for life, or imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine...",
        "bns_section": "105",
        "bns_description": "Punishment for culpable homicide not amounting to murder",
        "bns_text": "Whoever commits culpable homicide not amounting to murder, shall be punished with imprisonment for life, or imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine...",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No substantive changes",
        "category": "Offences Affecting Life",
        "punishment": "Life imprisonment or up to 10 years and fine"
    },
    {
        "ipc_section": "304A",
        "ipc_description": "Causing death by negligence",
        "ipc_text": "Whoever causes the death of any person by doing any rash or negligent act not amounting to culpable homicide, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.",
        "bns_section": "106",
        "bns_description": "Causing death by negligence",
        "bns_text": "Whoever causes death of any person by doing any rash or negligent act not amounting to culpable homicide, shall be punished with imprisonment of either description for a term which may extend to five years, and shall also be liable to fine.",
        "has_changes": True,
        "change_type": "substantive",
        "change_summary": "Enhanced punishment: increased from 2 to 5 years imprisonment. Fine is now mandatory ('shall' instead of 'or').",
        "category": "Offences Affecting Life",
        "punishment": "Up to 5 years imprisonment and fine"
    },
    {
        "ipc_section": "304B",
        "ipc_description": "Dowry death",
        "ipc_text": "Where the death of a woman is caused by any burns or bodily injury or occurs otherwise than under normal circumstances within seven years of her marriage and it is shown that soon before her death she was subjected to cruelty or harassment by her husband or any relative of her husband for, or in connection with, any demand for dowry, such death shall be called 'dowry death', and such husband or relative shall be deemed to have caused her death.",
        "bns_section": "80",
        "bns_description": "Dowry death",
        "bns_text": "Where the death of a woman is caused by any burns or bodily injury or occurs otherwise than under normal circumstances within seven years of her marriage and it is shown that soon before her death she was subjected to cruelty or harassment by her husband or any relative of her husband for, or in connection with, any demand for dowry, such death shall be called 'dowry death', and such husband or relative shall be deemed to have caused her death.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes - definition and scope remain identical",
        "category": "Offences Affecting Life",
        "punishment": "Minimum 7 years, may extend to life imprisonment"
    },
    {
        "ipc_section": "354",
        "ipc_description": "Assault or criminal force to woman with intent to outrage her modesty",
        "ipc_text": "Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term which shall not be less than one year but which may extend to five years, and shall also be liable to fine.",
        "bns_section": "74",
        "bns_description": "Assault or use of criminal force to woman with intent to outrage her modesty",
        "bns_text": "Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term which shall not be less than one year but which may extend to five years, and shall also be liable to fine.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No substantive changes",
        "category": "Sexual Offences",
        "punishment": "1 to 5 years imprisonment and fine"
    },
    {
        "ipc_section": "375",
        "ipc_description": "Rape",
        "ipc_text": "A man is said to commit 'rape' if he has sexual intercourse with a woman under circumstances falling under any of the seven descriptions...",
        "bns_section": "63",
        "bns_description": "Rape",
        "bns_text": "A man is said to commit 'rape' if he has sexual intercourse with a woman under circumstances falling under any of the descriptions...",
        "has_changes": False,
        "change_type": "linguistic",
        "change_summary": "Minor linguistic changes, core definition unchanged",
        "category": "Sexual Offences",
        "punishment": "Minimum 10 years, may extend to life imprisonment"
    },
    {
        "ipc_section": "376",
        "ipc_description": "Punishment for rape",
        "ipc_text": "Whoever commits rape shall be punished with rigorous imprisonment of either description for a term which shall not be less than ten years, but which may extend to imprisonment for life, and shall also be liable to fine.",
        "bns_section": "64",
        "bns_description": "Punishment for rape",
        "bns_text": "Whoever commits rape shall be punished with rigorous imprisonment of either description for a term which shall not be less than ten years, but which may extend to imprisonment for life, and shall also be liable to fine.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No substantive changes",
        "category": "Sexual Offences",
        "punishment": "Minimum 10 years to life imprisonment and fine"
    },
    {
        "ipc_section": "378",
        "ipc_description": "Theft",
        "ipc_text": "Whoever, intending to take dishonestly any moveable property out of the possession of any person without that person's consent, moves that property in order to such taking, is said to commit theft.",
        "bns_section": "303",
        "bns_description": "Theft",
        "bns_text": "Whoever, intending to take dishonestly any movable property out of the possession of any person without that person's consent, moves that property in order to such taking, is said to commit theft.",
        "has_changes": False,
        "change_type": "linguistic",
        "change_summary": "Spelling change: 'moveable' to 'movable'",
        "category": "Offences Against Property",
        "punishment": "Up to 3 years imprisonment or fine or both"
    },
    {
        "ipc_section": "379",
        "ipc_description": "Punishment for theft",
        "ipc_text": "Whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.",
        "bns_section": "303",
        "bns_description": "Punishment for theft",
        "bns_text": "Whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes",
        "category": "Offences Against Property",
        "punishment": "Up to 3 years imprisonment or fine or both"
    },
    {
        "ipc_section": "392",
        "ipc_description": "Punishment for robbery",
        "ipc_text": "Whoever commits robbery shall be punished with rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine.",
        "bns_section": "309",
        "bns_description": "Punishment for robbery",
        "bns_text": "Whoever commits robbery shall be punished with rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes",
        "category": "Offences Against Property",
        "punishment": "Up to 10 years rigorous imprisonment and fine"
    },
    {
        "ipc_section": "420",
        "ipc_description": "Cheating and dishonestly inducing delivery of property",
        "ipc_text": "Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
        "bns_section": "318",
        "bns_description": "Cheating and dishonestly inducing delivery of property",
        "bns_text": "Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes - popular '420' section retained",
        "category": "Offences Against Property",
        "punishment": "Up to 7 years imprisonment and fine"
    },
    {
        "ipc_section": "497",
        "ipc_description": "Adultery",
        "ipc_text": "Whoever has sexual intercourse with a person who is and whom he knows or has reason to believe to be the wife of another man, without the consent or connivance of that man, such sexual intercourse not amounting to the offence of rape, is guilty of the offence of adultery...",
        "bns_section": None,
        "bns_description": "Repealed/Decriminalized",
        "bns_text": None,
        "has_changes": True,
        "change_type": "repealed",
        "change_summary": "Adultery decriminalized by Supreme Court in Joseph Shine v. Union of India (2018). Not included in BNS.",
        "category": "Sexual Offences",
        "punishment": "N/A - Decriminalized"
    },
    {
        "ipc_section": "499",
        "ipc_description": "Defamation",
        "ipc_text": "Whoever, by words either spoken or intended to be read, or by signs or by visible representations, makes or publishes any imputation concerning any person intending to harm, or knowing or having reason to believe that such imputation will harm, the reputation of such person, is said to defame that person.",
        "bns_section": "356",
        "bns_description": "Defamation",
        "bns_text": "Whoever, by words either spoken or intended to be read, or by signs or by visible representations, makes or publishes any imputation concerning any person intending to harm, or knowing or having reason to believe that such imputation will harm, the reputation of such person, is said to defame that person.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes - defamation remains criminal offence",
        "category": "Defamation",
        "punishment": "Up to 2 years imprisonment or fine or both"
    },
    {
        "ipc_section": "500",
        "ipc_description": "Punishment for defamation",
        "ipc_text": "Whoever defames another shall be punished with simple imprisonment for a term which may extend to two years, or with fine, or with both.",
        "bns_section": "356",
        "bns_description": "Punishment for defamation",
        "bns_text": "Whoever defames another shall be punished with simple imprisonment for a term which may extend to two years, or with fine, or with both.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes",
        "category": "Defamation",
        "punishment": "Up to 2 years imprisonment or fine or both"
    },
    {
        "ipc_section": "503",
        "ipc_description": "Criminal intimidation",
        "ipc_text": "Whoever threatens another with any injury to his person, reputation or property, or to the person or reputation of any one in whom that person is interested, with intent to cause alarm to that person, or to cause that person to do any act which he is not legally bound to do, or to omit to do any act which that person is legally entitled to do, as the means of avoiding the execution of such threat, commits criminal intimidation.",
        "bns_section": "351",
        "bns_description": "Criminal intimidation",
        "bns_text": "Whoever threatens another with any injury to his person, reputation or property, or to the person or reputation of any one in whom that person is interested, with intent to cause alarm to that person, or to cause that person to do any act which he is not legally bound to do, or to omit to do any act which that person is legally entitled to do, as the means of avoiding the execution of such threat, commits criminal intimidation.",
        "has_changes": False,
        "change_type": "none",
        "change_summary": "No changes",
        "category": "Criminal Intimidation",
        "punishment": "Up to 2 years imprisonment or fine or both"
    }
]

LANDMARK_CASES = [
    {
        "case_name": "Kedar Nath Singh v. State of Bihar",
        "citation": "AIR 1962 SC 955",
        "court": "Supreme Court of India",
        "year": 1962,
        "judges": ["B.P. Sinha (CJ)", "J.C. Shah", "K. Subba Rao", "K.N. Wanchoo", "M. Hidayatullah"],
        "ipc_sections": ["124A"],
        "facts": "The appellant made a speech at a public meeting criticizing the Congress government, using strong language. He was charged under Section 124A IPC for sedition.",
        "legal_issues": "Whether Section 124A IPC is constitutionally valid? What is the scope of sedition?",
        "judgment_summary": "The Supreme Court upheld the constitutional validity of Section 124A but read it down. The Court held that sedition applies only when there is incitement to violence or intention to create public disorder.",
        "ratio_decidendi": "Section 124A is constitutional only when applied to acts involving intention or tendency to create disorder or incitement to violence. Criticism of government without inciting violence is not sedition.",
        "obiter_dicta": "Strong criticism of government policies is essential for democracy and is protected under Article 19(1)(a).",
        "validity_status": "requires_review",
        "validity_reasoning": "BNS Section 152 has substantially changed the sedition provision. It now requires 'purposely or knowingly' exciting secession, armed rebellion, or separatist activities. The Kedar Nath Singh test may need reconsideration under the new formulation."
    },
    {
        "case_name": "K.M. Nanavati v. State of Maharashtra",
        "citation": "AIR 1962 SC 605",
        "court": "Supreme Court of India",
        "year": 1962,
        "judges": ["B.P. Sinha (CJ)", "K. Subba Rao", "J.R. Mudholkar"],
        "ipc_sections": ["300", "302", "304"],
        "facts": "Naval Commander Nanavati shot Prem Ahuja after discovering his wife's affair with him. The case involved whether this was murder or culpable homicide not amounting to murder under grave and sudden provocation.",
        "legal_issues": "Whether the killing was under grave and sudden provocation (Exception 1 to Section 300)? Whether there was premeditation?",
        "judgment_summary": "The Supreme Court held it was murder, not culpable homicide. There was time gap between provocation and killing, and the act was premeditated. The Court clarified the test for 'grave and sudden provocation'.",
        "ratio_decidendi": "For Exception 1 to Section 300 to apply: (1) provocation must be grave and sudden, (2) the offender must act on the spur of the moment before cooling down, (3) the mode of retaliation must be proportionate.",
        "obiter_dicta": "The test is whether a reasonable person belonging to the same class of society would act in the same manner.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Sections 100, 101, 103, and 105 maintain the same distinction between murder and culpable homicide. The exceptions to Section 300 are preserved in BNS Section 101. This precedent remains fully applicable."
    },
    {
        "case_name": "State of Karnataka v. Appa Balu Ingale",
        "citation": "AIR 1993 SC 1126",
        "court": "Supreme Court of India",
        "year": 1993,
        "judges": ["M.N. Venkatachaliah (CJ)", "Yogeshwar Dayal"],
        "ipc_sections": ["304A"],
        "facts": "A driver of a State transport bus drove rashly, causing death of a passenger. The question was whether this constituted culpable homicide or death by negligence.",
        "legal_issues": "What distinguishes 'rash and negligent act' under Section 304A from culpable homicide under Section 299?",
        "judgment_summary": "The Court held that Section 304A applies when death is caused by rash or negligent act not amounting to culpable homicide. The distinction lies in the degree of knowledge and risk undertaken.",
        "ratio_decidendi": "Section 304A requires proof of rash or negligent act. Rashness implies hazarding dangerous consequences with knowledge of risk. Negligence is failure to exercise reasonable care. If there's knowledge that act is so dangerous as to cause death, it's culpable homicide.",
        "obiter_dicta": "The test is objective - what would a reasonable prudent person do in the circumstances.",
        "validity_status": "requires_review",
        "validity_reasoning": "BNS Section 106 has enhanced punishment for death by negligence from 2 to 5 years and made fine mandatory. While the legal principles remain valid, sentencing precedents under old Section 304A need reconsideration."
    },
    {
        "case_name": "Sushil Murmu v. State of Jharkhand",
        "citation": "(2004) 2 SCC 338",
        "court": "Supreme Court of India",
        "year": 2004,
        "judges": ["Y.K. Sabharwal", "C.K. Thakker"],
        "ipc_sections": ["304B"],
        "facts": "The appellant's wife died within 7 years of marriage under suspicious circumstances. There was evidence of dowry harassment. The husband was convicted under Section 304B.",
        "legal_issues": "What is the scope of Section 304B? What constitutes 'soon before death'? What is the nature of presumption?",
        "judgment_summary": "The Court held that all ingredients of Section 304B must be proved: (1) death within 7 years of marriage, (2) death under abnormal circumstances, (3) cruelty or harassment for dowry soon before death. The presumption under Section 113B Evidence Act is rebuttable.",
        "ratio_decidendi": "'Soon before death' is a relative term depending on circumstances. There must be proximate and live link between dowry death and cruelty. The prosecution must prove all ingredients except the causing of death, which is presumed.",
        "obiter_dicta": "Section 304B is a preventive measure against dowry deaths and must be strictly construed.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Section 80 retains Section 304B without any substantive changes. The entire legal framework, definitions, and presumptions remain identical. All precedents under IPC 304B are directly applicable to BNS Section 80."
    },
    {
        "case_name": "State of Maharashtra v. Madhukar Narayan Mardikar",
        "citation": "AIR 1991 SC 207",
        "court": "Supreme Court of India",
        "year": 1991,
        "judges": ["K.N. Singh", "M.M. Punchhi"],
        "ipc_sections": ["354"],
        "facts": "The accused removed the saree of a woman while she was sleeping. The issue was whether this constituted assault with intent to outrage modesty.",
        "legal_issues": "What constitutes 'outraging modesty' under Section 354? Is mere touching sufficient?",
        "judgment_summary": "The Court held that the act clearly outraged the woman's modesty. 'Modesty' is an attribute associated with female human beings and the act must be capable of shocking the sense of decency of a woman.",
        "ratio_decidendi": "For Section 354: (1) assault or criminal force on a woman, (2) intent to outrage or knowledge that modesty will be outraged. The essence is unwanted sexual contact or gesture violating dignity and modesty.",
        "obiter_dicta": "The test is objective - whether the act is capable of outraging modesty from the perspective of a reasonable woman.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Section 74 maintains Section 354 without any substantive changes. The definition of 'outraging modesty' and punishment remain identical. All precedents are fully applicable."
    },
    {
        "case_name": "Mukesh & Anr v. State of NCT of Delhi (Nirbhaya Case)",
        "citation": "(2017) 6 SCC 1",
        "court": "Supreme Court of India",
        "year": 2017,
        "judges": ["Dipak Misra (CJ)", "R. Banumathi", "Ashok Bhushan"],
        "ipc_sections": ["375", "376", "376D"],
        "facts": "Gang rape and murder of a young woman in Delhi in 2012. The case led to nationwide protests and amendments to rape laws.",
        "legal_issues": "Constitutionality of death penalty in rape-murder cases. Scope of mitigating circumstances.",
        "judgment_summary": "The Supreme Court upheld the death sentence, holding it was a 'rarest of rare case'. The brutality, planning, and absence of mitigating circumstances justified capital punishment.",
        "ratio_decidendi": "In rape-murder cases involving extreme brutality, the 'rarest of rare' doctrine applies. Courts must balance aggravating and mitigating circumstances. The crime's impact on society is relevant.",
        "obiter_dicta": "The Court emphasized that rape is a crime against humanity and dignity. The increase in such crimes requires deterrent punishment.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Sections 63 and 64 maintain the definition and punishment for rape without substantive changes. Section 70 deals with gang rape. All principles from this landmark judgment remain applicable under BNS."
    },
    {
        "case_name": "Pyare Lal Bhargava v. State of Rajasthan",
        "citation": "AIR 1963 SC 1094",
        "court": "Supreme Court of India",
        "year": 1963,
        "judges": ["B.P. Sinha (CJ)", "K. Subba Rao", "J.C. Shah"],
        "ipc_sections": ["378", "379"],
        "facts": "The accused took away timber belonging to the government. The issue was whether there was 'dishonest intention' at the time of taking.",
        "legal_issues": "What constitutes 'dishonest intention' under Section 378? When must the intention exist?",
        "judgment_summary": "The Court held that for theft, dishonest intention must exist at the time of taking. Taking property with honest claim of right, even if mistaken, is not theft.",
        "ratio_decidendi": "Essential ingredients of theft under Section 378: (1) dishonest intention to take property, (2) movable property, (3) taken out of possession of another, (4) without consent, (5) property moved. The intention must exist when the property is moved.",
        "obiter_dicta": "Dishonesty means doing something with knowledge that one has no legal right to do so.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Section 303 maintains the definition of theft with only linguistic changes (moveable→movable). All elements and legal principles remain identical. Precedent fully applicable."
    },
    {
        "case_name": "Bishwanath Prasad v. State of Bihar",
        "citation": "AIR 1971 SC 1305",
        "court": "Supreme Court of India",
        "year": 1971,
        "judges": ["I.D. Dua", "G.K. Mitter"],
        "ipc_sections": ["392"],
        "facts": "The accused snatched a gold chain from a woman's neck. The issue was whether snatching constitutes robbery or extortion.",
        "legal_issues": "What is the distinction between robbery, extortion, and theft?",
        "judgment_summary": "The Court held that robbery is theft with aggravated circumstances - either force/threat of force before/during theft to commit theft, or to retain stolen property, or to aid escape.",
        "ratio_decidendi": "For robbery under Section 392: theft or extortion must be committed, and in committing/attempting theft/extortion, the offender voluntarily causes or attempts to cause death/hurt/wrongful restraint/fear of instant death/hurt/wrongful restraint.",
        "obiter_dicta": "Robbery is a more serious offence than theft because it involves violence or threat.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Section 309 retains robbery provision without changes. The definition, elements, and punishment remain identical. All robbery precedents are fully applicable."
    },
    {
        "case_name": "Hridaya Ranjan Prasad Verma v. State of Bihar",
        "citation": "AIR 2000 SC 1821",
        "court": "Supreme Court of India",
        "year": 2000,
        "judges": ["S.P. Bharucha", "Doraiswamy Raju"],
        "ipc_sections": ["420"],
        "facts": "The accused obtained money by false representation regarding a business venture. The issue was ingredients of cheating.",
        "legal_issues": "What are the essential ingredients of cheating under Section 420?",
        "judgment_summary": "The Court laid down the ingredients of cheating: (1) fraudulent/dishonest inducement, (2) deceiving a person, (3) inducing delivery of property or consent to retain property, (4) mens rea - dishonest intention at the time of making promise.",
        "ratio_decidendi": "For Section 420: deception from the inception with dishonest intention. Mere breach of contract is not cheating unless fraudulent intention existed at inception. The representation must be false to the knowledge of accused.",
        "obiter_dicta": "Every civil wrong does not become a criminal offence. There must be mens rea.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Section 318 retains Section 420 without any changes. The popular '420' designation is maintained. All elements, mens rea requirements, and precedents are directly applicable."
    },
    {
        "case_name": "Joseph Shine v. Union of India",
        "citation": "(2018) 11 SCC 1",
        "court": "Supreme Court of India (Constitution Bench)",
        "year": 2018,
        "judges": ["Dipak Misra (CJ)", "R.F. Nariman", "A.M. Khanwilkar", "D.Y. Chandrachud", "Indu Malhotra"],
        "ipc_sections": ["497"],
        "facts": "Constitutional challenge to Section 497 IPC (adultery) as discriminatory and violative of Articles 14, 15, and 21.",
        "legal_issues": "Whether Section 497 is constitutionally valid? Does it violate gender equality and right to privacy?",
        "judgment_summary": "The Supreme Court struck down Section 497 IPC, holding it unconstitutional. The Court held adultery cannot be a criminal offence and the provision was discriminatory against women.",
        "ratio_decidendi": "Section 497 was arbitrary, archaic, and denied women dignity and agency. It treated women as property of husbands. Right to privacy includes autonomy in intimate decisions. Adultery may be ground for civil remedy but not criminal prosecution.",
        "obiter_dicta": "The law was a relic of Victorian morality incompatible with constitutional values of equality and dignity.",
        "validity_status": "valid",
        "validity_reasoning": "This judgment decriminalized adultery. BNS does not include adultery as a criminal offence, aligning with this ruling. The precedent remains valid and was incorporated into legislative reform."
    },
    {
        "case_name": "Subramanian Swamy v. Union of India",
        "citation": "(2016) 7 SCC 221",
        "court": "Supreme Court of India (Constitution Bench)",
        "year": 2016,
        "judges": ["Dipak Misra", "P.C. Pant"],
        "ipc_sections": ["499", "500"],
        "facts": "Constitutional challenge to criminal defamation provisions under Sections 499 and 500 IPC.",
        "legal_issues": "Whether Sections 499 and 500 violate Article 19(1)(a)? Are they reasonable restrictions?",
        "judgment_summary": "The Supreme Court upheld the constitutional validity of criminal defamation. The Court held that reputation is a fundamental right and criminal defamation is a reasonable restriction on free speech.",
        "ratio_decidendi": "Right to reputation is part of Article 21. Criminal defamation serves as deterrent and is proportionate restriction under Article 19(2). Civil remedy alone is insufficient. The provision is not arbitrary.",
        "obiter_dicta": "Many democracies retain criminal defamation. It balances free speech with right to reputation.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Section 356 retains criminal defamation without changes. The constitutional validity upheld in this case continues to apply. All principles and precedents are directly applicable."
    },
    {
        "case_name": "Shreya Singhal v. Union of India",
        "citation": "(2015) 5 SCC 1",
        "court": "Supreme Court of India",
        "year": 2015,
        "judges": ["J. Chelameswar", "R.F. Nariman"],
        "ipc_sections": ["499", "500", "503"],
        "facts": "Constitutional challenge to Section 66A of IT Act. Also dealt with related IPC provisions on causing annoyance and criminal intimidation.",
        "legal_issues": "Scope of free speech online. Validity of vague penal provisions.",
        "judgment_summary": "The Court struck down Section 66A IT Act as unconstitutional. Clarified that causing annoyance or inconvenience cannot criminalize speech unless it creates public disorder or incites violence.",
        "ratio_decidendi": "Penal provisions affecting free speech must be narrowly tailored and not vague. The advocacy-incitement test applies. Discussion, advocacy, and criticism cannot be criminalized merely because they cause annoyance.",
        "obiter_dicta": "The internet is a medium for free speech and excessive restrictions stifle democratic discourse.",
        "validity_status": "valid",
        "validity_reasoning": "BNS Sections 351 (criminal intimidation) and 356 (defamation) remain unchanged. The principles of narrow tailoring and advocacy-incitement test established here continue to apply in interpreting these provisions."
    }
]
